name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.1

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: mkdir -p output && go build -v -o output/hot-hacker-news cmd/main.go
    - name: Run tests
      run: go test -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hot-hacker-news
        path: output/hot-hacker-news
